### ISSUE TITLE
An problem about project setting for Armor Paint in UE4.

### ISSUE THREAD

**Issue by RobinArtemstein** [armory3d/armorpaint_unreal#1]
Hello, I had been using Armor Paint and following your GitHub since 2018, I really like it and it is very helpful for my projects,

This is my first time to try the UE4 plugin,  I downloaded it, extracted to my UE4, this is my exact path for the plugin:

C:/Users/Robin Artemstein/Documents/Unreal Projects/daztest/Plugins/armorpaint_unreal

Then I did restart Unreal Editor, the button of Armor Paint really showed up on the tool list, I imported an OBJ model and selected it, I tried to paint texture map with Armor Paint, an error massage showed up:

"Please configure folder where ArmorPaint is located at 'Project Settings - Plugins - ArmorPaint"

I had done the project setting and configured the plugin folder to the above-mentioned path, but the same error massage still showed up.

Thank you in advance for any answers.

Cheers.

**Comment by AlfioSaitta** [comment]
Same issue for me, and the ArmoPaint icon is not visible.

Unreal Engine 4.24.3 on Linux, builded from sources and pluin compiled as system plugin (not as project plugin)

![image](https://user-images.githubusercontent.com/10280718/78181366-8713e100-7464-11ea-8a4c-cf9a39e29eff.png)

**Comment by Hunanbean** [comment]
@RobinArtemstein
I had a similar problem. I had compiled armorpaint from source, and the file name to execute it was krom.exe. i had to change krom.exe to ArmorPaint.exe then the button in Unreal worked.

also, make sure that in the project settings you are pointing it to the ArmorPaint program directory, and not trying to point it to the plugins directory

**Comment by Hunanbean** [comment]
@AlfioSaitta
When i have the toolbar set to show small icons, the ArmorPaint plugin icon dissappears. It shows when the toolbar is set to show normal sized icons for me.
Although I highly suspect you are having a very different issue than that.

**Comment by AlfioSaitta** [comment]
@Hunanbean... of course, i had to modify some parts of the sources to correct the path problems

**Comment by luboslenco** [comment]
Updated the plugin and fixed the missing small icon. When compiling ArmorPaint from source please make sure the binary is named `ArmorPaint.exe` like already mentioned. Help on the Linux version welcome!
