### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by Calinou** [armory3d/armorpaint_unreal#2]
This repository currently has no license attached. I'd suggest adding the [same license as ArmorPaint itself](https://github.com/armory3d/armorpaint/blob/master/LICENSE.md) just in case :slightly_smiling_face: 

See also https://github.com/armory3d/armorpaint_unity/issues/3.

**Comment by luboslenco** [comment]
Fixed, thanks. https://github.com/armory3d/armorpaint_unreal/commit/56adcf49b024c162fcee44931c80ec08f7088eed
