### ISSUE TITLE
Building for UE4.25

### ISSUE THREAD

**Issue by kgkatzonis** [armory3d/armorpaint_unreal#4]
Hello! I'm trying to build the plugin for UE4.25 but I get an LNK2019 error:

`LNK2019	unresolved external symbol "__declspec(dllimport) public: static void __cdecl FStaticMeshOperations::ConvertHardEdgesToSmoothGroup(struct FMeshDescription const &,class TArray<unsigned int,class TSizedDefaultAllocator<32> > &)" (__imp_?ConvertHardEdgesToSmoothGroup@FStaticMeshOperations@@SAXAEBUFMeshDescription@@AEAV?$TArray@IV?$TSizedDefaultAllocator@$0CA@@@@@@Z) referenced in function "public: void __cdecl FArmorPaintModule::PluginButtonClicked(void)" (?PluginButtonClicked@FArmorPaintModule@@QEAAXXZ)`

**Comment by NihilisticJedi** [comment]
I don't want be that guy BUT- Did you by any chance find a fix as I have the exact same error

**Comment by kgkatzonis** [comment]
Sorry but no. I didn't manage to find a fix.

**Comment by Wolfos** [comment]
How do you even compile it? It never gets added to my project's source. It just tells me that it failed to compile and to retry manually.

**Comment by Rizzlord** [comment]
still the error...

**Comment by GreenMoonMoon** [comment]
From what I can gather, "ConvertHardEdgesToSmoothGroup" is no longer exported by the FStaticMeshOperations module where it has been moved. I've submitted the issue (Case # 00261751).
Meanwhile we still can use "MeshDescriptionOperations", it will compile and link with warning.

**Comment by luboslenco** [comment]
Updated now, thanks for report!
