### ISSUE TITLE
Export from UE4 4.26 - Exception sening empty arrays

### ISSUE THREAD

**Issue by shadowtj** [armory3d/armorpaint_unreal#8]
Got the following error when exporting from UE4 4.26 to Armour paint inside the armour paint plugin

LoginId:cc90b7244a915d5a730c1099050e3d45
EpicAccountId:6e177c6b8187421093aa51fbb175539e

Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:C:\Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\Containers/Array.h] [Line: 674] Array index out of bounds: 0 from an array of size 0

UE4Editor_Core
UE4Editor_Core
UE4Editor_ArmorPaint!DispatchCheckVerify<void,<lambda_0c3cf21ceff4d2e7019f999672d36c56> >() [C:\Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\Misc\AssertionMacros.h:165]
UE4Editor_ArmorPaint!FArmorPaintModule::PluginButtonClicked() [G:\projects\CharacterCreator\test\Plugins\ArmorPaint\Source\ArmorPaint\Private\ArmorPaint.cpp:119]
UE4Editor_ArmorPaint!TBaseRawMethodDelegateInstance<0,FArmorPaintModule,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [C:\Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:469]
UE4Editor_Slate

**Comment by luboslenco** [comment]
Updated to support UE5 now. Thanks for report.
